import {importDocument,renderSource,closeDocuments,boundedZip,JSZip} from './documents.mjs';
import {createDecisions,saveBlob,assetURL} from './assets.mjs';
import {csv,escapeHTML as esc,cancelled,pause} from './core.mjs';
import {createCatalogue,makeChronology,collateEvents,ungroup,eventOrder,validateCatalogue,ENGINE_VERSION} from './chronology.mjs';
const $=id=>document.getElementById(id),sources=[],issues=[],decisions=createDecisions();
let catalogue=createCatalogue(),busy=false,controller=null,page=0,selected=null,renderAt=0,omittedPage=0;
const PAGE=50,focusCache=new Map();
function status(text=''){ $('status').textContent=text; }
function setBusy(value){busy=value;for(const id of ['add','choose','build','save','session-open','clear','manual','files-button'])$(id).disabled=value;$('stop').hidden=!value;$('stop').disabled=!value;}
function mentions(e){return e.mentionIds.map(id=>catalogue.mentions.find(m=>m.id===id)).filter(Boolean);}
function sourceLabel(m){const s=sources.find(s=>s.id===m.sourceId);return `${s?.name||'Missing source'} · ${m.locator||''}`;}
function visible(){const filter=$('filter').value;return catalogue.events.filter(e=>filter==='excluded'?e.excluded:!e.excluded&&(filter==='all'||filter==='focus'&&e.relevance>=.5||filter==='undated'&&(!e.date||e.dateReason)||filter==='review'&&!e.reviewed&&(!e.date||e.dateReason||e.uncertain))).sort(eventOrder);}
function render(){const list=visible();page=Math.min(page,Math.max(0,Math.ceil(list.length/PAGE)-1));$('output').hidden=!catalogue.events.length;$('drop').hidden=Boolean(sources.length||catalogue.events.length);$('count').textContent=`${list.length} events`;$('files-button').textContent=sources.length?`Files (${sources.length})`:'Files';$('summary').textContent=sources.length?`${sources.length} documents${issues.length?' · Check Files for unreadable material':''}`:'';
  const body=$('rows');body.replaceChildren();for(const e of list.slice(page*PAGE,(page+1)*PAGE)){
    const ms=mentions(e),tr=document.createElement('tr');tr.dataset.id=e.id;tr.tabIndex=0;tr.classList.toggle('selected',e.id===selected);
    const d=e.date?e.date+(e.dateEnd?' – '+e.dateEnd:''):e.dateText||'Undated';
    tr.innerHTML=`<td>${esc(d)}${e.dateReason?'<span class="subtle">Date uncertain</span>':''}</td><td>${esc(e.text)}${e.note?`<span class="subtle">${esc(e.note)}</span>`:''}</td><td><button class="source-button">${esc(ms.length?sourceLabel(ms[0]):'Manual entry')}</button>${ms.length>1?`<span class="subtle">+ ${ms.length-1} other ${ms.length===2?'mention':'mentions'}</span>`:''}</td>`;
    tr.onclick=()=>inspect(e.id);tr.onkeydown=ev=>{if(ev.key==='Enter')inspect(e.id);};body.append(tr);
  }
  $('prev').disabled=!page;$('next').disabled=(page+1)*PAGE>=list.length;$('page-info').textContent=list.length?`${page*PAGE+1}–${Math.min((page+1)*PAGE,list.length)} of ${list.length}`:'No events in this view';
}
function closeInspector(){selected=null;$('inspector').hidden=true;$('work').classList.remove('inspecting');render();}
async function inspect(id){const e=catalogue.events.find(e=>e.id===id);if(!e)return;selected=id;render();$('inspector').hidden=false;$('work').classList.add('inspecting');
  $('editor').innerHTML=`<label for="edit-event">Event</label><textarea id="edit-event" rows="3">${esc(e.text)}</textarea><label for="edit-date">Date</label><input id="edit-date" type="date" value="${esc(e.date)}"><label for="edit-end">End date (only for an interval)</label><input id="edit-end" type="date" value="${esc(e.dateEnd||'')}">${e.dateReason?`<p class="mini">${esc(e.dateReason)}</p>`:''}<label for="edit-note">Note</label><textarea id="edit-note" rows="2">${esc(e.note||'')}</textarea><div class="actions"><button id="apply-edit" class="primary">Save changes</button><button id="remove-entry">${e.excluded?'Restore':'Remove'}</button>${e.mentionIds.length>1?'<button id="ungroup">Separate mentions</button>':''}</div>`;
  $('apply-edit').onclick=()=>{const text=$('edit-event').value.trim(),date=$('edit-date').value,dateEnd=$('edit-end').value;if(!text)return status('Enter an event description.');if(dateEnd&&(!date||dateEnd<date))return status('The end date must follow the start date.');Object.assign(e,{text,date,dateEnd,note:$('edit-note').value,edited:true,reviewed:true,dateReason:''});focusCache.clear();render();status('Changes saved.');};
  $('remove-entry').onclick=()=>{e.excluded=!e.excluded;e.edited=true;closeInspector();};
  if($('ungroup'))$('ungroup').onclick=async()=>{if(busy)return;ungroup(catalogue,e);await operation(async signal=>collateEvents(catalogue,decisions,{signal}));closeInspector();};
  const nav=$('source-nav');nav.replaceChildren();$('source-preview').replaceChildren();const ms=mentions(e);
  for(const [i,m]of ms.entries()){const button=document.createElement('button');button.textContent=`Source ${i+1}`;button.title=sourceLabel(m);button.onclick=()=>showSource(e,m,button);nav.append(button);}
  if(ms.length)await showSource(e,ms[0],nav.firstChild);
}
async function showSource(e,m,button){for(const b of $('source-nav').children)b.setAttribute('aria-pressed',String(b===button));
  const s=sources.find(s=>s.id===m.sourceId),block=s?.blocks.find(b=>b.id===m.blockId),host=document.createElement('div');$('source-preview').replaceChildren(host);
  if(!block||block.text.slice(m.start,m.end)!==m.quote){host.textContent='The source passage no longer matches.';return;}
  const meta=document.createElement('p');meta.className='mini';meta.textContent=[s.from&&`From: ${s.from}`,m.communicated&&`Document dated ${m.communicated}`,m.quoted&&'Quoted correspondence'].filter(Boolean).join(' · ');host.append(meta);
  const original=document.createElement('div');host.append(original);try{await renderSource(s,block,original,{start:m.start,end:m.end});}catch(error){original.textContent=error.message;}
}
async function operation(fn){if(busy)return;controller=new AbortController();setBusy(true);try{return await fn(controller.signal);}catch(e){status(e.name==='AbortError'?'Stopped. Completed work is retained.':e.message);if(e.name!=='AbortError')console.error(e);}finally{setBusy(false);render();}}
async function addFiles(files){await operation(async signal=>{for(const file of files){cancelled(signal);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');if(sources.some(s=>s.inputHash===hash))continue;
    try{const imported=await importDocument(file,{revision:$('revision').value,useOCR:$('ocr').checked,signal,progress:status});for(const [i,s]of imported.entries()){s.inputHash=i===0?hash:null;sources.push(s);}for(const s of imported)for(const warning of s.warnings)issues.push({file:s.name,error:warning});}
    catch(e){if(e.name==='AbortError')throw e;issues.push({file:file.name,error:e.message});}render();await pause();
  }status(`${sources.length} documents ready. Make a chronology${$('focus').value.trim()?' with this focus':''}.`);});}
function partialEvents(){const ids=new Set(catalogue.events.flatMap(e=>e.mentionIds));for(const m of catalogue.mentions)if(!ids.has(m.id))catalogue.events.push({id:m.id,mentionIds:[m.id],text:m.text,date:m.date,dateEnd:m.dateEnd,dateText:m.dateText,dateReason:m.dateReason,uncertain:m.uncertain,note:'',edited:false,reviewed:false,excluded:false});}
async function applyFocus(signal){const focus=$('focus').value.trim();if(!focus){$('filter').value='all';return;}
  for(const e of catalogue.events){cancelled(signal);const key=focus+'\0'+e.text;let score=focusCache.get(key);if(score==null){score=(await decisions.rank(e.text,focus,'',signal)).noul;focusCache.set(key,score);}e.relevance=score;}$('filter').value='focus';
}
async function build(){if(!sources.length){status('Add documents first.');return;}closeInspector();await operation(async signal=>{
  try{status('Finding events…');await makeChronology(sources,catalogue,decisions,{signal,deep:$('thorough').checked,onProgress:p=>{partialEvents();if(performance.now()-renderAt>400){renderAt=performance.now();render();}status(p.phase==='discover'?'Finding events…':'Collecting repeated mentions…');}});await applyFocus(signal);page=0;status('');}
  finally{partialEvents();}
});}
function rowsForExport(){return visible().map(e=>[e.date+(e.dateEnd?' – '+e.dateEnd:''),e.text,mentions(e).map(sourceLabel).join('\n'),e.note||'']);}
async function saveSession(){return operation(async()=>{const zip=new JSZip(),manifest={format:'event-strip',version:2,engine:ENGINE_VERSION,focus:$('focus').value,catalogue,sources:sources.map(({file,...s})=>({...s,stored:`sources/${s.id}.${s.kind}`,originalName:file.name,lastModified:file.lastModified,mimeType:file.type})),issues};zip.file('session.json',JSON.stringify(manifest));for(const s of sources)zip.file(`sources/${s.id}.${s.kind}`,s.file);const blob=await zip.generateAsync({type:'blob',compression:'STORE'});saveBlob(blob,'event-strip-session.zip');status('Session saved with original files.');return blob;});}
function migrateLegacy(data,restored){const cat=createCatalogue(),ids=new Set();for(const row of data.rows||[]){const s=restored.find(s=>s.id===row.sourceId),b=s?.blocks.find(b=>b.id===row.blockId);if(!b)throw new Error('An older entry has a missing source.');let start=row.start,end=row.end;while(start<end&&/\s/.test(b.text[start]))start++;while(end>start&&/\s/.test(b.text[end-1]))end--;const id=`${s.id}:${b.id}:${start}:${end}`;if(ids.has(id))continue;ids.add(id);const quote=b.text.slice(start,end);const m={id,sourceId:s.id,blockId:b.id,start,end,quote,text:quote,date:row.date||'',dateEnd:'',dateText:row.dateText||'',dateReason:row.dateReason||'Imported from the previous date-based version.',dateOptions:[],locator:b.locator,communicated:s.communicated||'',quoted:Boolean(b.quoted),uncertain:!row.reviewed};cat.mentions.push(m);cat.events.push({...m,mentionIds:[id],note:row.note||'',edited:Boolean(row.reviewed||row.note),reviewed:Boolean(row.reviewed),excluded:false});}return cat;}
async function openSession(file){if(!file)return;return operation(async()=>{const bytes=await file.arrayBuffer();boundedZip(bytes);const zip=await JSZip.loadAsync(bytes),entry=zip.file('session.json');if(!entry)throw new Error('Not an Event Strip session.');const data=JSON.parse(await entry.async('string'));if(data.format!=='event-strip'||![1,2].includes(data.version)||!Array.isArray(data.sources))throw new Error('Unsupported session format.');const restored=[];
  for(const s of data.sources){if(typeof s.id!=='string'||!Array.isArray(s.blocks)||!zip.file(s.stored))throw new Error('Invalid source manifest.');const blob=await zip.file(s.stored).async('blob');restored.push({...s,file:new File([blob],s.originalName||s.name.split(' / ').at(-1),{lastModified:s.lastModified||0,type:s.mimeType||''})});}
  const replacement=data.version===1?migrateLegacy(data,restored):validateCatalogue(data.catalogue,restored);await closeDocuments();sources.splice(0,sources.length,...restored);catalogue=replacement;issues.splice(0,issues.length,...(data.issues||[]));$('focus').value=data.focus||'';$('filter').value='all';focusCache.clear();page=0;closeInspector();status(data.version===1?'Older chronology restored. Make chronology to discover additional events.':'Session restored.');
});}
function showOmitted(){const host=$('omitted-list');host.replaceChildren();const shown=catalogue.omitted.slice(0,++omittedPage*30);for(const m of shown){const p=document.createElement('div');p.className='omitted';const quote=document.createElement('p');quote.textContent=m.quote;const source=document.createElement('small');source.textContent=sourceLabel(m);const include=document.createElement('button');include.textContent='Include as event';include.onclick=()=>{const value={...m,text:m.quote,date:'',dateEnd:'',dateText:'',dateReason:'Set the date after reviewing the source.',uncertain:false,dateOptions:[]};catalogue.mentions.push(value);catalogue.omitted=catalogue.omitted.filter(x=>x.id!==m.id);partialEvents();render();showOmitted();};p.append(quote,source,document.createElement('br'),include);host.append(p);}$('more-omitted').hidden=shown.length===catalogue.omitted.length;}
function showFiles(){const host=$('coverage-body');host.replaceChildren();for(const s of sources){const p=document.createElement('div');p.className='file-row';p.textContent=s.name;host.append(p);}for(const i of issues){const p=document.createElement('p');p.className='error';p.textContent=`${i.file}: ${i.error}`;host.append(p);}if(!sources.length)host.textContent='No files added.';omittedPage=0;showOmitted();$('coverage').showModal();}
$('add').onclick=$('choose').onclick=()=>$('files').click();$('files').onchange=e=>{addFiles([...e.target.files]);e.target.value='';};$('build').onclick=build;$('stop').onclick=()=>controller?.abort();$('files-button').onclick=showFiles;$('more-omitted').onclick=showOmitted;$('close-inspector').onclick=closeInspector;$('filter').onchange=()=>{page=0;render();};$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};$('save').onclick=saveSession;$('session-open').onclick=()=>$('session').click();$('session').onchange=e=>{openSession(e.target.files[0]);e.target.value='';};
$('export').onclick=()=>saveBlob(new Blob([csv(['Date','Event','Sources','Note'],rowsForExport())],{type:'text/csv;charset=utf-8'}),'chronology.csv');
$('copy').onclick=async()=>{try{const rows=rowsForExport(),safe=v=>(/^[=+@\-\t\r]/.test(v)?"'":'')+v;const plain=[['Date','Event','Sources'],...rows.map(r=>r.slice(0,3))].map(r=>r.map(v=>safe(v).replace(/[\t\n\r]+/g,' ')).join('\t')).join('\n');const html='<table><thead><tr><th>Date</th><th>Event</th><th>Sources</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+r.slice(0,3).map(v=>'<td>'+esc(safe(v)).replace(/\n/g,'<br>')+'</td>').join('')+'</tr>').join('')+'</tbody></table>';if(globalThis.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/plain':new Blob([plain],{type:'text/plain'}),'text/html':new Blob([html],{type:'text/html'})})]);else await navigator.clipboard.writeText(plain);status('Chronology copied.');}catch(e){status('Clipboard unavailable. Use Export CSV.');}};
$('manual').onclick=()=>{const id=crypto.randomUUID();catalogue.events.push({id,text:'New event',date:'',dateEnd:'',dateReason:'',mentionIds:[],note:'',edited:true,reviewed:false,manual:true});render();inspect(id);};
$('clear').onclick=async()=>{if(!confirm('Clear this session? Save it first to keep your work.'))return;await closeDocuments();decisions.close();sources.length=issues.length=0;catalogue=createCatalogue();focusCache.clear();closeInspector();status();};
for(const b of document.querySelectorAll('dialog .close'))b.onclick=()=>b.closest('dialog').close();$('about').onclick=async()=>{$('about-dialog').showModal();$('build-info').textContent=await(await fetch(assetURL('build-info.json'))).text();$('licenses').textContent=await(await fetch(assetURL('NOTICES.txt'))).text();};
document.body.addEventListener('dragover',e=>{e.preventDefault();$('drop').classList.add('over');});document.body.addEventListener('dragleave',()=>$('drop').classList.remove('over'));document.body.addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('over');if(e.dataTransfer.files.length)addFiles([...e.dataTransfer.files]);});
$('demo').onclick=()=>addFiles([new File(['Construction commenced on 3 May 2026 and was substantially complete by 18 September 2026.\n\nJones inspected the property on 4 April 2026.\n\nThe pump failed.\n\nThis document is confidential.'],'Example - project.txt'),new File(['Work on the building began on 3 May 2026.'],'Example - progress note.txt')]);
window.EventStrip={sources,get catalogue(){return catalogue;},get rows(){return catalogue.events;},get busy(){return busy;},get omitted(){return catalogue.omitted;},addFiles,build,decisions,saveSession,openSession,visible,inspect};render();window.addEventListener('beforeunload',e=>{if(catalogue.events.length){e.preventDefault();e.returnValue='';}});
