import {importDocument,renderSource,closeDocuments,boundedZip,JSZip} from './documents.mjs';
import {createDecisions,saveBlob,assetURL} from './assets.mjs';
import {eventCandidates,rowOrder,statuses,stateForEvent,csv,escapeHTML,uid,cancelled,pause} from './core.mjs';
const $=id=>document.getElementById(id),sources=[],rows=[],importIssues=[];let controller=null,page=0,selected=null,showSeq=0,busy=false;const PAGE=50;
const decisions=createDecisions();
function status(text){$('status').textContent=text;}
function setBusy(value){busy=value;$('stop').disabled=!value;$('stop').hidden=!value;$('build').disabled=value;$('add').disabled=value;$('save').disabled=value;$('clear').disabled=value;$('session-open').disabled=value;}
function visible(){const mode=$('filter').value;return rows.filter(r=>mode==='all'||mode==='events'&&r.status!=='not_event'||mode==='unresolved'&&(!r.date||r.dateReason||r.status==='unclear'||r.status==='unreviewed')||mode==='proposed'&&['planned','requested','conditional'].includes(r.status)||mode==='quoted'&&r.quoted).sort(rowOrder);}
function render(){const list=visible();page=Math.min(page,Math.max(0,Math.ceil(list.length/PAGE)-1));$('empty').hidden=rows.length>0;$('table').hidden=!rows.length;$('count').textContent=`${list.length.toLocaleString()} entries`;const body=$('rows');body.replaceChildren();for(const r of list.slice(page*PAGE,(page+1)*PAGE)){
  const source=sources.find(s=>s.id===r.sourceId),tr=document.createElement('tr');tr.dataset.id=r.id;tr.classList.toggle('selected',selected===r.id);tr.tabIndex=0;
  tr.innerHTML=`<td class="date-cell">${escapeHTML(r.date||'Unresolved')}<span class="raw-date">${escapeHTML(r.dateText||'No explicit date')}</span>${r.dateReason?'<span class="badge warn">Check date</span>':''}</td><td class="date-cell">${escapeHTML(r.communicated||'Not established')}</td><td class="statement"><p>${escapeHTML(r.quote)}</p><div class="source-name">${escapeHTML(source?.name||'Missing source')}${r.quoted?' · quoted correspondence':''}</div></td><td><span class="badge ${['unclear','unreviewed'].includes(r.status)?'warn':''}">${escapeHTML(r.status==='unreviewed'?'Pending':statuses[r.status]||r.status)}</span>${r.reviewed?'<span class="small">Reviewed</span>':''}${r.error?'<span class="small error">Needs review</span>':''}</td>`;
  tr.onclick=()=>select(r.id);tr.onkeydown=e=>{if(e.key==='Enter')select(r.id);};body.append(tr);
} $('page-info').textContent=list.length?`${page*PAGE+1}–${Math.min((page+1)*PAGE,list.length)} of ${list.length.toLocaleString()}`:'No entries in this view';$('prev').disabled=page===0;$('next').disabled=(page+1)*PAGE>=list.length;}
async function select(id){selected=id;render();const r=rows.find(x=>x.id===id),source=sources.find(s=>s.id===r.sourceId),block=source.blocks.find(b=>b.id===r.blockId);const turn=++showSeq;
  $('editor').innerHTML=`<label for="edit-date">Event date · source wording: ${escapeHTML(r.dateText||'none')}</label><input id="edit-date" type="date" value="${escapeHTML(r.date)}">${r.dateReason?`<p class="small">${escapeHTML(r.dateReason)}${r.dateAlternatives?.length?' · '+r.dateAlternatives.map(escapeHTML).join(' or '):''}</p>`:''}<label for="edit-status">Assertion status</label><select id="edit-status">${Object.entries(statuses).map(([key,label])=>`<option value="${key}" ${r.status===key?'selected':''}>${key==='unreviewed'?'Pending':label}</option>`).join('')}</select><label for="edit-note">Your note (separate from source text)</label><textarea id="edit-note">${escapeHTML(r.note)}</textarea><div class="actions"><button id="apply-edit" class="primary">Accept correction</button><button id="undo-edit">Undo last correction</button></div>${r.error?`<p class="small error">${escapeHTML(r.error)}</p>`:''}`;
  $('apply-edit').onclick=()=>{r.previous={date:r.date,status:r.status,note:r.note,dateReason:r.dateReason,reviewed:r.reviewed};r.date=$('edit-date').value;r.status=$('edit-status').value;r.note=$('edit-note').value;r.dateReason='';r.reviewed=true;r.error='';render();status('Correction saved in this session. Export to keep it.');};
  $('undo-edit').disabled=!r.previous;$('undo-edit').onclick=()=>{if(r.previous){Object.assign(r,r.previous);delete r.previous;select(r.id);}};
  $('source-preview').replaceChildren();try{await renderSource(source,block,$('source-preview'),{start:r.start,end:r.end});if(turn!==showSeq)return;}catch(e){if(turn===showSeq)$('source-preview').textContent=e.message;}
}
async function addFiles(files){if(busy)return;controller=new AbortController();setBusy(true);let added=0;try{for(const file of files){cancelled(controller.signal);if(sources.some(s=>s.name===file.name&&s.file.size===file.size&&s.file.lastModified===file.lastModified))continue;try{const imported=await importDocument(file,{revision:$('revision').value,useOCR:$('ocr').checked,signal:controller.signal,progress:status});for(const source of imported){sources.push(source);rows.push(...eventCandidates(source));added++;}render();}catch(e){if(e.name==='AbortError')throw e;importIssues.push({file:file.name,error:e.message});status(`${file.name}: ${e.message}`);}await pause();}status(added?`Added ${added} documents.`:'No new documents added.');}catch(e){status(e.name==='AbortError'?'Import stopped. Completed documents retained.':e.message);}finally{setBusy(false);render();}if(added&&!controller.signal.aborted)await build(false);}
async function build(force=true){if(busy||!rows.length){if(!rows.length)status('Add documents first.');return;}controller=new AbortController();setBusy(true);let done=0;const focus=$('focus').value.trim();try{await decisions.start();for(const r of rows){cancelled(controller.signal);if(r.reviewed||(!force&&r.status!=='unreviewed'))continue;const source=sources.find(s=>s.id===r.sourceId),state=stateForEvent(r,source);try{
  const answer=await decisions.decide(state,{type:'choice',instructions:'Classify the event associated with TARGET DATE in TARGET SENTENCE. Do not turn a plan, request, denial or quotation into a completed act.',criteria:{completed:'An act is reported as already done',planned:'Future, planned, proposed or scheduled',requested:'An action is requested or demanded',denied:'The act is expressly denied',conditional:'Only if a stated condition occurs',reported:'An attributed report, not asserted here',unclear:'Date-event relation or status unclear',not_event:'No event associated with this date'}},controller.signal);
  r.status=answer.choice;r.modelProbabilities=answer.probabilities;r.error='';
  if(focus){const fit=await decisions.decide(state,{type:'noul',instructions:`Does the target sentence substantively concern: ${focus}`,criteria:{true:'Addresses this focus',false:'Does not address this focus'}},controller.signal);r.relevance=fit.noul;}
}catch(e){if(e.name==='AbortError')throw e;r.error=e.message;throw e;}done++;if(done%3===0){render();await pause();}status('Building chronology…');}status(`Chronology built. ${rows.filter(r=>r.status==='unclear'||!r.date).length} entries need date or context review.`);}catch(e){status(e.name==='AbortError'?'Stopped. Completed judgments and human corrections retained.':`Chronology could not finish: ${e.message}`);}finally{setBusy(false);render();}}
function exportRows(){return visible().map(r=>{const s=sources.find(x=>x.id===r.sourceId),b=s.blocks.find(x=>x.id===r.blockId);return [r.date,r.dateText,r.communicated,statuses[r.status],r.quote,s.name,b.locator,s.from||'',r.quoted?'Quoted':'',r.note,r.dateReason,r.error||'',r.reviewed?'Human reviewed':'Model/unreviewed'];});}
const head=['Event date','Date wording','Communicated on','Assertion status','Exact source wording','Source','Locator','Communication author','Quoted material','Human note','Date caveat','Processing issue','Review'];
async function saveSession(){if(busy)return;setBusy(true);try{status('Saving sources and corrections locally…');const zip=new JSZip(),manifest={format:'event-strip',version:1,focus:$('focus').value,rows,sources:sources.map(({file,...s})=>({...s,stored:`sources/${s.id}.${s.kind}`})),issues:importIssues};zip.file('session.json',JSON.stringify(manifest));for(const s of sources)zip.file(`sources/${s.id}.${s.kind}`,s.file);saveBlob(await zip.generateAsync({type:'blob',compression:'STORE'}),'event-strip-session.zip');status('Session saved, including original files.');}catch(e){status(e.message);}finally{setBusy(false);}}
async function openSession(file){if(!file||busy)return;setBusy(true);try{const bytes=await file.arrayBuffer();boundedZip(bytes);const zip=await JSZip.loadAsync(bytes),entry=zip.file('session.json');if(!entry)throw new Error('Not an Event Strip session.');const data=JSON.parse(await entry.async('string'));if(data.format!=='event-strip'||data.version!==1||!Array.isArray(data.sources)||!Array.isArray(data.rows))throw new Error('Unsupported session format.');const restored=[];for(const s of data.sources){if(typeof s.id!=='string'||!Array.isArray(s.blocks)||!zip.file(s.stored))throw new Error('Invalid source manifest.');const blob=await zip.file(s.stored).async('blob');restored.push({...s,file:new File([blob],s.name.split(' / ').at(-1))});}const valid=new Map(restored.map(s=>[s.id,s]));for(const r of data.rows)if(!valid.get(r.sourceId)?.blocks.some(b=>b.id===r.blockId))throw new Error('A row refers to an absent source.');await closeDocuments();sources.splice(0,sources.length,...restored);rows.splice(0,rows.length,...data.rows);importIssues.splice(0,importIssues.length,...(data.issues||[]));$('focus').value=data.focus||'';page=0;selected=null;render();status('Session restored. Original sources and corrections are available.');}catch(e){status(e.message);}finally{setBusy(false);}}
$('add').onclick=()=>$('files').click();$('files').onchange=e=>{addFiles([...e.target.files]);e.target.value='';};$('build').onclick=build;$('stop').onclick=()=>{controller?.abort();status('Stopping after the active operation…');};$('filter').onchange=()=>{page=0;render();};$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};$('export').onclick=()=>saveBlob(new Blob([csv(head,exportRows())],{type:'text/csv;charset=utf-8'}),'event-strip.csv');$('copy').onclick=async()=>{try{const data=[head,...exportRows()].map(x=>x.map(v=>(/^[=+@\-\t\r]/.test(String(v??''))?"'":'')+String(v??'').replace(/[\t\r\n]+/g,' ')).join('\t')).join('\n');await navigator.clipboard.writeText(data);status('Visible table copied.');}catch{status('Clipboard unavailable. Use Export CSV.');}};$('save').onclick=saveSession;$('session-open').onclick=()=>$('session').click();$('session').onchange=e=>openSession(e.target.files[0]);
$('clear').onclick=async()=>{if(busy||!confirm('Clear this session? Export first to keep corrections.'))return;await closeDocuments();decisions.close();sources.length=rows.length=importIssues.length=0;selected=null;page=0;$('editor').textContent='Select an entry.';$('source-preview').replaceChildren();render();status('Session cleared.');};
$('issues').onclick=()=>{$('coverage-body').innerHTML=`<p>${sources.length} documents · ${sources.reduce((n,s)=>n+s.blocks.length,0)} readable blocks. Input failures and unreadable areas:</p><ul>${[...importIssues.map(x=>`${x.file}: ${x.error}`),...sources.flatMap(s=>s.warnings.map(w=>`${s.name}: ${w}`))].map(x=>`<li>${escapeHTML(x)}</li>`).join('')||'<li>No unreadable areas or import failures reported.</li>'}</ul><table><thead><tr><th>Source</th><th>Blocks</th><th>Communication date</th></tr></thead><tbody>${sources.map(s=>`<tr><td>${escapeHTML(s.name)}</td><td>${s.blocks.length}</td><td>${escapeHTML(s.communicated||'Unknown')}</td></tr>`).join('')}</tbody></table>`;$('coverage').showModal();};
$('about').onclick=async()=>{$('about-dialog').showModal();try{$('build-info').textContent=await(await fetch(assetURL('build-info.json'))).text();$('licenses').textContent=await(await fetch(assetURL('NOTICES.txt'))).text();}catch(e){$('build-info').textContent=e.message;}};for(const button of document.querySelectorAll('dialog .close'))button.onclick=()=>button.closest('dialog').close();
for(const target of [document.body]){target.addEventListener('dragover',e=>{e.preventDefault();$('drop').classList.add('over');});target.addEventListener('dragleave',()=>$('drop').classList.remove('over'));target.addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('over');if(e.dataTransfer.files.length)addFiles([...e.dataTransfer.files]);});}
$('demo').onclick=()=>addFiles([new File(['From: Jordan Example <jordan@example.invalid>\r\nTo: Alex Example <alex@example.invalid>\r\nDate: Thu, 12 Mar 2026 10:00:00 -0600\r\nSubject: SAMPLE ONLY - Courier status\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nThe courier collected the notice on 10 March 2026. Delivery is scheduled for 13 March 2026.\r\n\r\nOn 9 March 2026 we requested an extension, but it has not been agreed.\r\n'],'SAMPLE - courier.eml',{type:'message/rfc822'})]);
window.EventStrip={sources,rows,addFiles,build,decisions,saveSession,openSession,get busy(){return busy;}};window.addEventListener('beforeunload',e=>{if(rows.length){e.preventDefault();e.returnValue='';}});render();
