import {assetURL,createDecisions} from './assets.mjs';
import {uid,compileQuery,passageWindows,escapeHTML,cancelled,pause} from './core.mjs';
import {importDocument,renderSource} from './documents.mjs';
const $=id=>document.getElementById(id),PAGE=30;let mode='tabs',originId=Number(new URL(location.href).searchParams.get('origin'))||null,worker=null,dbReady=null,nextId=0,controller=null,queryId='',total=0,page=0,items=[],tabItems=[],localSources=[],selected=null,judging=false;
const pending=new Map();const decisions=createDecisions(s=>$('model-status').textContent=s);
const status=s=>$('status').textContent=s;
function request(type,data={},progress){const id=++nextId;return new Promise((resolve,reject)=>{pending.set(id,{resolve,reject,progress});worker.postMessage({id,type,...data});});}
async function corpus(){if(dbReady)return dbReady;worker=new Worker(assetURL('corpus-worker.js'));worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;if(data.event){p.progress?.(data);return;}pending.delete(data.id);if(data.error){const e=new Error(data.error);e.name=data.name||'Error';p.reject(e);}else p.resolve(data.result);};worker.onerror=e=>{for(const p of pending.values())p.reject(new Error(e.message));pending.clear();dbReady=null;};dbReady=request('init',{assets:Object.fromEntries(['duckdb-browser-eh.worker.js','duckdb-eh.wasm'].map(n=>[n,assetURL(n)]))});return dbReady;}
function setBusy(b){$('search').disabled=b;$('stop').disabled=!b;$('index-all').disabled=b;$('add-folder').disabled=b;$('add-parquet').disabled=b;$('add-docs').disabled=b;}
async function refreshPage(){if(mode==='corpus'){await corpus();items=await request('page',{queryId,offset:page*PAGE,limit:PAGE,sort:$('sort').value});}else items=($('sort').value==='fit'?[...tabItems].sort((a,b)=>(b.score??-1)-(a.score??-1)):tabItems).slice(page*PAGE,(page+1)*PAGE);render();}
function render(){const holder=$('results');holder.replaceChildren();for(const r of items){const row=document.createElement('article');row.className='result'+(selected?.id===r.id?' selected':'');row.tabIndex=0;row.innerHTML=`<h3>${escapeHTML(r.title)}</h3><p>${escapeHTML(r.text)}</p><div class="meta"><span>${escapeHTML(r.citation||r.dataset||'')}</span><span>${escapeHTML(r.locator)}</span><span>${escapeHTML(r.language||'')}</span><span class="badge">${r.score==null?escapeHTML(r.status||'Not judged'):`Fit ${r.score.toFixed(2)} / 3`}</span>${r.error?'<span class="error">Judgment unavailable</span>':''}</div>`;row.onclick=()=>select(r);row.onkeydown=e=>{if(e.key==='Enter')select(r);};holder.append(row);}$('count').textContent=total.toLocaleString();$('page-info').textContent=total?`${page*PAGE+1}–${Math.min(total,(page+1)*PAGE)} of ${total.toLocaleString()}`:'No passages found in searched sources';$('prev').disabled=page===0;$('next').disabled=(page+1)*PAGE>=total;}
async function invoke(tabId,method,args=[]){const [r]=await chrome.scripting.executeScript({target:{tabId},func:async(m,a)=>{try{return {value:await globalThis.PinpointerLensPage[m](...a)};}catch(e){return {error:e.message};}},args:[method,args]});if(!r?.result||r.result.error)throw new Error(r?.result?.error||'Tab did not respond');return {value:r.result.value,documentId:r.documentId};}
async function tabSearch(query,signal){const compiled=compileQuery(query),all=await chrome.tabs.query({});let origin=all.find(t=>t.id===originId);if(!origin){origin=all.find(t=>t.active&&/^https?:/.test(t.url||''))||all.find(t=>/^https?:/.test(t.url||''));originId=origin?.id;}
  const scope=$('scope').value,targets=all.filter(t=>/^https?:/.test(t.url||'')&&(!origin||Boolean(t.incognito)===Boolean(origin.incognito))&&(scope==='all'||scope==='current'&&t.id===originId||scope==='group'&&origin?.groupId>=0&&t.groupId===origin.groupId&&t.windowId===origin.windowId));let scanned=0;const errors=[];
  if(scope==='group'&&(!origin||origin.groupId<0))errors.push('Origin tab is not in a group. Choose All tabs or Origin tab.');
  for(const tab of targets){cancelled(signal);if(tab.discarded||tab.frozen){errors.push(`${tab.title}: discarded/frozen tab; activate it and search again.`);continue;}try{await chrome.scripting.executeScript({target:{tabId:tab.id},files:['lens-dist/page.js']});const info=await invoke(tab.id,'collect');for(let offset=0;offset<info.value.count;offset+=64){cancelled(signal);const pageData=await invoke(tab.id,'slice',[offset,64]);if(pageData.documentId!==info.documentId)throw new Error('Tab reloaded during search.');for(const block of pageData.value)for(const w of passageWindows(block.text))if(compiled.test(w.text)){tabItems.push({id:uid(),seq:tabItems.length,title:tab.title,url:tab.url,tabId:tab.id,windowId:tab.windowId,documentId:info.documentId,handle:info.value,blockIndex:block.index,text:w.text,start:w.start,end:w.end,locator:block.locator,score:null,status:'Not judged'});}total=tabItems.length;await refreshPage();}scanned++;status(`Searched ${scanned}/${targets.length} tabs · ${total} matching passages`);}catch(e){errors.push(`${tab.title}: ${e.message}`);}}
  for(const source of localSources)for(const block of source.blocks)for(const w of passageWindows(block.text)){cancelled(signal);if(compiled.test(w.text))tabItems.push({id:uid(),seq:tabItems.length,title:source.name,sourceId:source.id,blockId:block.id,text:w.text,start:w.start,end:w.end,locator:block.locator,score:null,status:'Not judged'});}
  total=tabItems.length;$('coverage').textContent=`${scanned}/${targets.length} tabs; ${localSources.length} imported documents; ${errors.length} unavailable sources`;
  $('coverage').title=errors.join('\n');status(errors.length?`Search finished with ${errors.length} source issues. Hover the coverage line for details.`:`Searched all ${scanned} tabs and imported documents. ${total} matches.`);
}
async function search(){if(controller)return;try{compileQuery($('query').value);}catch(e){status(e.message);return;}queryId=uid();page=0;total=0;tabItems=[];items=[];selected=null;controller=new AbortController();setBusy(true);render();try{
  if(mode==='corpus'){await corpus();const result=await request('search',{query:$('query').value,queryId,filters:{language:$('language').value,dataset:$('dataset').value.trim(),from:$('from').value,to:$('to').value}},async event=>{if(event.phase==='search'){total=event.total;status(`Searching every registered file · ${event.filesDone} complete · ${event.documents.toLocaleString()} candidate documents · ${total.toLocaleString()} passages`);if(page===0)await refreshPage();}else if(event.error)status(`${event.path}: ${event.error}`);});total=result.total;$('coverage').textContent=`${result.filesDone} files searched · ${result.documents.toLocaleString()} candidate documents · ${result.errors.length} failed files`;$('coverage').title=result.errors.map(x=>`${x.path}: ${x.error}`).join('\n');status(result.complete?`Search complete across all registered files. ${total.toLocaleString()} matches.`:'Search incomplete: failed files are listed in coverage.');}
  else await tabSearch($('query').value,controller.signal);
  await refreshPage();if($('distinction').value.trim()&&!controller.signal.aborted)await judge(controller.signal);
}catch(e){status(e.name==='AbortError'?'Stopped. Already found passages are retained.':e.message);}finally{controller=null;setBusy(false);}}
async function judge(signal){if(judging)return;const distinction=$('distinction').value.trim();if(!distinction){status('Enter the distinction to judge.');return;}judging=true;let done=0;try{await decisions.start();for(let offset=0;offset<total;offset+=PAGE){cancelled(signal);const batch=mode==='corpus'?await request('page',{queryId,offset,limit:PAGE}):tabItems.slice(offset,offset+PAGE);for(const r of batch){cancelled(signal);try{const a=await decisions.decide(`SOURCE PASSAGE:\n${r.text}`,{type:'score',instructions:`How directly does this passage address: ${distinction}`,criteria:['Unrelated','Vocabulary only','Relevant discussion','Directly addresses the distinction']},signal);r.score=a.score;r.probabilities=a.probabilities;r.status='Judged';r.error='';}catch(e){if(e.name==='AbortError')throw e;r.error=e.message;r.status='Not judged: context or runtime error';}if(mode==='corpus')await request('update',{item:r});done++;if(done%3===0){await refreshPage();status(`Judged ${done.toLocaleString()} / ${total.toLocaleString()} passages · exact matches remain visible`);await pause();}}}status(`Judged ${done.toLocaleString()} passages. All original matches are retained.`);}finally{judging=false;await refreshPage();}}
async function select(r){selected=r;render();const p=$('preview');p.innerHTML=`<h3>${escapeHTML(r.title)}</h3><pre>${escapeHTML(r.text)}</pre><p class="small">${escapeHTML(r.locator)}${r.error?' · '+escapeHTML(r.error):''}</p><button id="open-passage" class="primary">Open exact passage</button>${r.license?`<p class="small">${escapeHTML(r.license)}</p>`:''}`;$('open-passage').onclick=async()=>{try{if(r.tabId){await chrome.windows.update(r.windowId,{focused:true});await chrome.tabs.update(r.tabId,{active:true});const [result]=await chrome.scripting.executeScript({target:{tabId:r.tabId,documentIds:[r.documentId]},func:(handle,index,start,end,text)=>globalThis.PinpointerLensPage.go(handle,index,start,end,text),args:[r.handle,r.blockIndex,r.start,r.end,r.text]});if(!result?.result)throw new Error('Source navigation did not complete.');}else if(r.sourceId){const s=localSources.find(x=>x.id===r.sourceId);await renderSource(s,s.blocks.find(b=>b.id===r.blockId),p,{start:r.start,end:r.end});}else{const source=await request('read',{item:r});p.replaceChildren();const h=document.createElement('h3');h.textContent=r.title;p.append(h);const pre=document.createElement('pre');pre.textContent=source.text.slice(Math.max(0,source.start-1200),source.end+1200);p.append(pre);if(/^https?:/.test(r.url)){const a=document.createElement('a');a.href=r.url;a.target='_blank';a.rel='noopener';a.textContent='Open original source website';p.append(a);}}}catch(e){status(e.message);}};}
async function showCatalog(){try{await corpus();const files=await request('list');$('catalog-status').textContent=`${files.length} local Parquet files · ${files.reduce((n,f)=>n+f.count,0).toLocaleString()} records · ${files.filter(f=>f.indexed).length} fully indexed. Every registered file is searched, including unindexed tails.`;$('file-list').innerHTML=`<table><thead><tr><th>File</th><th>Rows</th><th>Indexed</th><th></th></tr></thead><tbody>${files.map(f=>`<tr><td>${escapeHTML(f.path)}${f.error?'<span class="error">'+escapeHTML(f.error)+'</span>':''}</td><td>${f.count.toLocaleString()}</td><td>${f.processed.toLocaleString()}</td><td><button data-remove="${f.id}">Remove</button></td></tr>`).join('')}</tbody></table>`;for(const button of $('file-list').querySelectorAll('[data-remove]'))button.onclick=async()=>{await request('remove',{fileId:button.dataset.remove});showCatalog();};}catch(e){$('catalog-status').textContent=e.message;}}
async function addEntries(entries){await corpus();setBusy(true);try{const result=await request('add',{entries},e=>$('catalog-status').textContent=`Registering ${e.done}/${e.total} files`);await showCatalog();if(result.errors.length)$('catalog-status').textContent+=' Failures: '+result.errors.map(x=>`${x.path}: ${x.error}`).join('; ');}catch(e){status(e.message);}finally{setBusy(false);}}
$('add-folder').onclick=async()=>{try{const root=await window.showDirectoryPicker({id:'a2aj-corpus',mode:'read'}),entries=[];async function walk(handle,prefix){for await(const [name,child]of handle.entries()){if(child.kind==='directory')await walk(child,prefix+name+'/');else if(/\.parquet$/i.test(name))entries.push({path:prefix+name,handle:child});}}await walk(root,root.name+'/');await addEntries(entries);}catch(e){if(e.name!=='AbortError')status(e.message);}};
$('add-parquet').onclick=()=>$('parquets').click();$('parquets').onchange=e=>addEntries([...e.target.files].map(f=>({path:f.webkitRelativePath||f.name,file:f})));$('index-all').onclick=async()=>{if(controller)return;controller=new AbortController();setBusy(true);try{await corpus();await request('index',{},e=>{const s=e.error?`${e.path}: ${e.error}`:`Indexing ${e.path} · ${e.processed?.toLocaleString()} / ${e.total?.toLocaleString()}`;$('catalog-status').textContent=s;status(s);});status('Full-corpus indexing pass finished. Review any file errors.');}catch(e){status(e.name==='AbortError'?'Indexing paused. Resume keeps completed batches.':e.message);}finally{controller=null;setBusy(false);showCatalog();}};
$('search').onclick=search;$('stop').onclick=()=>{controller?.abort();worker?.postMessage({type:'cancel'});status('Stopping…');};$('judge').onclick=async()=>{if(controller)return;controller=new AbortController();setBusy(true);try{await judge(controller.signal);}catch(e){status(e.message);}finally{controller=null;setBusy(false);}};$('prev').onclick=()=>{page--;refreshPage();};$('next').onclick=()=>{page++;refreshPage();};
for(const [button,next]of [['tabs-mode','tabs'],['corpus-mode','corpus']])$(button).onclick=()=>{if(controller)return;mode=next;$('tabs-mode').setAttribute('aria-pressed',String(mode==='tabs'));$('corpus-mode').setAttribute('aria-pressed',String(mode==='corpus'));$('scope-label').hidden=mode==='corpus';items=[];tabItems=[];total=0;page=0;render();if(mode==='corpus'){showCatalog();$('catalog').showModal();}};
$('files-button').onclick=()=>{showCatalog();$('catalog').showModal();};$('catalog').querySelector('.close').onclick=()=>$('catalog').close();$('origin').onclick=async()=>{const tabs=await chrome.tabs.query({active:true});const t=tabs.find(t=>/^https?:/.test(t.url||''));if(t){originId=t.id;status(`Origin: ${t.title}`);}else status('Activate the source webpage, then open this panel.');};$('wide').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL(`lens-dist/lens.html?origin=${originId||''}`)});
$('add-docs').onclick=()=>$('documents').click();$('documents').onchange=async e=>{try{for(const f of e.target.files)localSources.push(...await importDocument(f,{progress:status}));status(`${localSources.length} local documents ready for tab/document search.`);}catch(err){status(err.message);}};
$('copy').onclick=async()=>{if(!selected)return;try{await navigator.clipboard.writeText(`${selected.text}\n${selected.title}${selected.citation?' — '+selected.citation:''}, ${selected.locator}${selected.url?'\n'+selected.url:''}`);status('Original passage and locator copied.');}catch(e){status(e.message);}};
$('clear').onclick=()=>{if(controller)return;if(queryId&&worker)request('clear',{queryId}).catch(e=>status(e.message));queryId=uid();total=0;page=0;items=[];tabItems=[];selected=null;$('query').value='';$('distinction').value='';$('preview').replaceChildren();render();};$('query').onkeydown=e=>{if(e.key==='Enter')search();};
window.PinpointerLens={corpus,request,decisions,search};
$('sort').onchange=()=>{page=0;refreshPage();};
