// Original corpus files remain authoritative; only indexes and query excerpts persist.
let opening;
const request=req=>new Promise((ok,bad)=>{req.onsuccess=()=>ok(req.result);req.onerror=()=>bad(req.error);});
export async function database(){return opening ||= new Promise((ok,bad)=>{const r=indexedDB.open('pinpointer-lens-v1',3);r.onupgradeneeded=()=>{const db=r.result;for(const name of ['files','settings','index','results','vectors'])if(!db.objectStoreNames.contains(name))db.createObjectStore(name);const results=r.transaction.objectStore('results');if(!results.indexNames.contains('byScore'))results.createIndex('byScore',['queryId','rank','seq']);};r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error);});}
export async function get(store,key){const db=await database();return request(db.transaction(store).objectStore(store).get(key));}
export async function put(store,key,value){const db=await database();return new Promise((ok,bad)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=ok;tx.onerror=()=>bad(tx.error);tx.onabort=()=>bad(tx.error||new Error('Storage write aborted'));});}
export async function remove(store,key){const db=await database();return new Promise((ok,bad)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=ok;tx.onerror=()=>bad(tx.error);});}
export async function all(store){const db=await database();return request(db.transaction(store).objectStore(store).getAll());}
export async function putBatch(store,entries){const db=await database();return new Promise((ok,bad)=>{const tx=db.transaction(store,'readwrite'),s=tx.objectStore(store);for(const [k,v]of entries)s.put(v,k);tx.oncomplete=ok;tx.onerror=()=>bad(tx.error);tx.onabort=()=>bad(tx.error||new Error('Storage transaction aborted'));});}
export async function range(store,lower,upper,limit=Infinity){const db=await database();return new Promise((ok,bad)=>{const out=[],r=db.transaction(store).objectStore(store).openCursor(IDBKeyRange.bound(lower,upper));r.onerror=()=>bad(r.error);r.onsuccess=()=>{const c=r.result;if(!c||out.length>=limit)return ok(out);out.push([c.key,c.value]);c.continue();};});}
export async function deleteWhere(store,predicate){const db=await database();return new Promise((ok,bad)=>{const tx=db.transaction(store,'readwrite'),r=tx.objectStore(store).openCursor();r.onsuccess=()=>{const c=r.result;if(c){if(predicate(c.key,c.value))c.delete();c.continue();}};tx.oncomplete=ok;tx.onerror=()=>bad(tx.error);tx.onabort=()=>bad(tx.error||new Error('Storage cleanup aborted'));});}
export async function scorePage(queryId,offset,limit){const db=await database();return new Promise((ok,bad)=>{const out=[],r=db.transaction('results').objectStore('results').index('byScore').openCursor(IDBKeyRange.bound([queryId,-100,0],[queryId,100,Number.MAX_SAFE_INTEGER]));let skip=offset;r.onerror=()=>bad(r.error);r.onsuccess=()=>{const c=r.result;if(!c||out.length>=limit)return ok(out);if(skip){const n=skip;skip=0;c.advance(n);return;}out.push(c.value);c.continue();};});}
export async function postingRows(fileId,term,prefix){const db=await database();return new Promise((ok,bad)=>{const out=new Set(),lower=[fileId,term,0],upper=prefix?[fileId,term+'\uffff',Number.MAX_SAFE_INTEGER]:[fileId,term,Number.MAX_SAFE_INTEGER],r=db.transaction('index').objectStore('index').openCursor(IDBKeyRange.bound(lower,upper));r.onerror=()=>bad(r.error);r.onsuccess=()=>{const c=r.result;if(!c)return ok(out);for(const n of c.value)out.add(n);c.continue();};});}
export async function deleteRange(store,lower,upper){const db=await database();return new Promise((ok,bad)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(IDBKeyRange.bound(lower,upper));tx.oncomplete=ok;tx.onerror=()=>bad(tx.error);});}
export async function atomic(operations){const db=await database();return new Promise((ok,bad)=>{const tx=db.transaction([...new Set(operations.map(x=>x.store))],'readwrite');for(const x of operations)tx.objectStore(x.store).put(x.value,x.key);tx.oncomplete=ok;tx.onerror=()=>bad(tx.error);tx.onabort=()=>bad(tx.error||new Error('Index checkpoint aborted'));});}
export async function* scanBlocks(store,fileId){let after=-1;for(;;){const batch=await range(store,[fileId,after+1],[fileId,Number.MAX_SAFE_INTEGER],8);if(!batch.length)return;for(const [key,value]of batch){after=key[1];yield value;}}}
