[package]
name = "legal-structure-browser-engine"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
legal-structure = { git = "https://github.com/eliziff/legal-structure-parser.git", rev = "34ba3e75eaddf45c95058ed1eb68d4aa3fa42d15", features = ["provider-text", "citator"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
