import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createCatalogue,makeChronology,sameEvent,validateCatalogue} from '../src/chronology.mjs';
const assetsRoot=new URL('../../lens-dist/assets/',import.meta.url),assets={};
for(const name of ['model.onnx','tokenizer.json','tokenizer_config.json','rl_agent_config.json','ort-wasm-simd-threaded.wasm'])assets[name]=new Blob([await readFile(new URL(name,assetsRoot))]);
assets['ort-wasm-simd-threaded.mjs']=new URL('ort-wasm-simd-threaded.mjs',assetsRoot).href;
let id=0,calls=0;const pending=new Map();globalThis.self=globalThis;
globalThis.postMessage=data=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);data.error?p.reject(new Error(data.error)):p.resolve(data.result);};
await import('../src/decision-worker.mjs');
const call=(type,args)=>new Promise((resolve,reject)=>{const n=++id;calls++;pending.set(n,{resolve,reject});self.onmessage({data:{id:n,type,...args}});});
const initialized=call('init',{assets});
const decisions={start:()=>initialized,decide:(state,question)=>call('decide',{state,question}),rank:(text,query)=>call('rank',{text,query,context:''})};
const corpus=JSON.parse(await readFile(new URL('chronology-fixtures.json',import.meta.url),'utf8'));
const cat=createCatalogue();const start=performance.now();await makeChronology(corpus.sources,cat,decisions);
const checks=[];const check=(name,fn)=>{try{fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.message});}};
console.log('ACTUAL EVENTS',JSON.stringify(cat.events,null,2));console.log('MENTIONS',JSON.stringify(cat.mentions,null,2));console.log('OMITTED',JSON.stringify(cat.omitted,null,2));
check('Different construction milestones in a single sentence become distinct events',()=>{const rows=cat.mentions.filter(m=>m.sourceId==='project');assert.equal(rows.length,2);assert.deepEqual(rows.map(m=>m.date),['2026-05-03','2026-09-18']);});
check('A concrete undated event is retained',()=>{const m=cat.mentions.find(m=>m.sourceId==='undated');assert.ok(m);assert.equal(m.date,'');});
check('A heading, confidentiality boilerplate and greeting do not become events',()=>assert.ok(!cat.mentions.some(m=>m.sourceId==='header')));
check('Document date is not substituted for the described event date',()=>assert.equal(cat.mentions.find(m=>m.sourceId==='dates')?.date,'2026-05-03'));
check('A hospital stay spanning two dates is one event with an interval',()=>{const rows=cat.mentions.filter(m=>m.sourceId==='medical');assert.equal(rows.length,1);assert.equal(rows[0].date,'2026-06-10');assert.equal(rows[0].dateEnd,'2026-06-12');});
check('Non-legal employment event discovered',()=>assert.equal(cat.mentions.find(m=>m.sourceId==='job')?.date,'2026-07-07'));
check('French meeting event discovered',()=>assert.equal(cat.mentions.find(m=>m.sourceId==='french')?.date,'2026-08-08'));
check('Ambiguous numeric dates and missing years stay unresolved',()=>{assert.equal(cat.mentions.find(m=>m.sourceId==='ambiguous')?.date,'');assert.equal(cat.mentions.find(m=>m.sourceId==='missing-year')?.date,'');});
check('Original spans validate against their sources',()=>validateCatalogue(cat,corpus.sources));
const pairResults=[];for(const pair of corpus.pairs){const result=await sameEvent(pair.a,pair.b,decisions);pairResults.push({...pair,result});check('Event matching: '+pair.a.text+' / '+pair.b.text,()=>assert.equal(result,pair.same));}
check('Same construction start collects multiple sources',()=>assert.ok(cat.events.some(e=>e.mentionIds.some(id=>id.startsWith('project:'))&&e.mentionIds.some(id=>id.startsWith('progress:')))));
const before=calls;await makeChronology(corpus.sources,cat,decisions);check('Rebuilding unchanged documents reuses discovery and matching',()=>assert.equal(calls,before));
const evidence={passed:checks.every(c=>c.passed),runtime:'Actual packaged Laya ONNX with ONNX Runtime Web WASM; no mocked judgments',ms:performance.now()-start,calls,checks,pairResults,catalogue:cat};
await mkdir(new URL('../dist/',import.meta.url),{recursive:true});await writeFile(new URL('../dist/chronology-validation.json',import.meta.url),JSON.stringify(evidence,null,2));console.log(JSON.stringify({passed:evidence.passed,checks,pairResults},null,2));assert.ok(evidence.passed,'Chronology acceptance failed; inspect saved actual outputs.');
